/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    HeroiconsArrowDown20Solid: typeof import('~icons/heroicons/arrow-down20-solid')['default']
    HeroiconsDocumentTextSolid: typeof import('~icons/heroicons/document-text-solid')['default']
    HeroiconsGlobeAlt: typeof import('~icons/heroicons/globe-alt')['default']
    HeroiconsMicrophoneSolid: typeof import('~icons/heroicons/microphone-solid')['default']
    HeroiconsPaperAirplaneSolid: typeof import('~icons/heroicons/paper-airplane-solid')['default']
    HeroiconsPaperClip20Solid: typeof import('~icons/heroicons/paper-clip20-solid')['default']
    HeroiconsTrashSolid: typeof import('~icons/heroicons/trash-solid')['default']
    HeroiconsXMark20Solid: typeof import('~icons/heroicons/x-mark20-solid')['default']
    MessageBox: typeof import('./src/components/MessageBox.vue')['default']
    ModalBox: typeof import('./src/components/ModalBox.vue')['default']
    NotificationStack: typeof import('./src/components/NotificationStack.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
