# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Widget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build widget
        commit_user_name: Builder Bot
    - name: Purge jsDelivr cache
      uses: gacts/purge-jsdelivr-cache@v1.0.2
      with:
        url: |
            https://cdn.jsdelivr.net/gh/cheshire-cat-ai/widget-vue@main/example/widget.js
            https://cdn.jsdelivr.net/gh/cheshire-cat-ai/widget-vue@main/example/widget.css
        attempts: 3
