# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Widget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - name: Purge jsDelivr cache
      # You may pin to the exact commit or the version.
      # uses: gacts/purge-jsdelivr-cache@71fc7e172e0ef9559bfd251f43d75cf39cbeedba
      uses: gacts/purge-jsdelivr-cache@v1.0.2
      with:
        # URLs for the cache purging (string|list)
        url: |
            https://cdn.jsdelivr.net/gh/cheshire-cat-ai/widget-vue@main/example/widget.js
            https://cdn.jsdelivr.net/gh/cheshire-cat-ai/widget-vue@main/example/widget.css
        # Retry attempts (on the request failing)
        attempts: 3
